name: "XOXO- Dev Container Prebuild (hormigasais-lab)"

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  # 1. TRABAJO DE DEPENDENCIA: Verifica la existencia del archivo .XOXO_TOKEN_READY 
  #    en el repositorio de Thrumanshow para autorizar la ejecución.
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Repositorio Fuente (Thrumanshow)
        uses: actions/checkout@v3
        with:
          repository: Thrumanshow/Thrumanshow
          path: thrumanshow-source
          
      - name: Verificar Token de XOXO
        id: token_check
        run: |
          TOKEN_PATH="./thrumanshow-source/.XOXO_TOKEN_READY"
          
          echo "Buscando el token de dependencia: ${TOKEN_PATH}"
          
          if [ -f "$TOKEN_PATH" ]; then
            echo "✅ ¡Token de XOXO encontrado! La dependencia está satisfecha."
          else
            echo "❌ ¡ERROR! El token .XOXO_TOKEN_READY NO fue encontrado en el repositorio de Thrumanshow."
            # Forzamos el fallo para detener todo el flujo de trabajo
            exit 1 
          fi

  # 2. TRABAJO PRINCIPAL: Pre-construye el Dev Container, solo si la dependencia pasa.
  prebuild:
    # DEPENDENCIA CONFIGURADA: Este trabajo solo se ejecuta si 'dependency_check' tiene éxito.
    needs: [dependency_check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio actual (hormigasais-lab)
        uses: actions/checkout@v3

      - name: Configurar Entorno (Variables LAB)
        # Define variables que son útiles para la instalación y el entorno final.
        run: |
          echo "LAB_PATH=/home/usuario/hormigasais-lab" >> $GITHUB_ENV
          echo "LAB_PYTHON=python3" >> $GITHUB_ENV
          echo "Variables de entorno LAB configuradas."

      - name: Instalar Dependencias de Python (requirements.txt)
        # Pre-instala las dependencias para que el Dev Container sea instantáneo.
        run: ${{ env.LAB_PYTHON }} -m pip install -r requirements.txt

      - name: Setup Codespaces Prebuild
        # El paso que crea y guarda el ambiente de desarrollo.
        uses: github/codespaces-prebuild@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          prebuild-name: "XOXO- Dev Container HormigasAIS Prebuild"
          branch: ${{ github.ref_name }}
          devcontainer-path: ".devcontainer/devcontainer.json"
          wait-for-completion: true

      - name: Notify on Success
        if: success()
        run: echo "✅ Prebuild for ${{ github.ref_name }} completed successfully."

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Prebuild for ${{ github.ref_name }} failed. Check Actions logs."
