#!/usr/bin/env sh
###############################################################################
# Gradle start up script for UN*X
###############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m"

# Use the maximum available, or set by GRADLE_OPTS
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="$DEFAULT_JVM_OPTS"
fi

# Resolve real path to this script, resolving any symlinks
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done

SAVED="`pwd`"
cd `dirname "$PRG"`/gradle/wrapper
CLASSPATH=gradle-wrapper.jar
cd "$SAVED"

exec java $GRADLE_OPTS -classpath